apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: matrix
  name: bulletin-center
  labels:
    app: bulletin-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulletin-center
  template:
    metadata:
      name: bulletin-center
      labels:
        app: bulletin-center
    spec:
      serviceAccountName: bulletin-center-service-account
      restartPolicy: Always
      containers:
        - name: bulletin-center
          image: registry-vpc.cn-hangzhou.aliyuncs.com/shishaodong/spring-matrix-bulletin-center:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 1000Mi
            requests:
              cpu: 2000m
              memory: 1000Mi
          readinessProbe:
            httpGet:
              port: 2022
              path: /actuator/health/readiness
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 2022
              path: /actuator/health/liveness
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
